// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package api

import "strconv"

type Action byte

const (
	ActionNone     Action = 0
	ActionRequest  Action = 1
	ActionResponse Action = 2
)

var EnumNamesAction = map[Action]string{
	ActionNone:     "None",
	ActionRequest:  "Request",
	ActionResponse: "Response",
}

var EnumValuesAction = map[string]Action{
	"None":     ActionNone,
	"Request":  ActionRequest,
	"Response": ActionResponse,
}

func (v Action) String() string {
	if s, ok := EnumNamesAction[v]; ok {
		return s
	}
	return "Action(" + strconv.FormatInt(int64(v), 10) + ")"
}
